export const url = 'https://norma.nomoreparties.space/api';

export const dataOrders = [
    {
      id: '#111111',
      date: 'Сегодня, 16:20 i-GMT+3',
      name: 'Death Start Starship Main бургер',
      ingredients: [
        {
          "_id": "60d3b41abdacab0026a733c6",
          "name": "Краторная булка N-200i",
          "type": "bun",
          "proteins": 80,
          "fat": 24,
          "carbohydrates": 53,
          "calories": 420,
          "price": 1255,
          "image": "https://code.s3.yandex.net/react/code/bun-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c8",
          "name": "Филе Люминесцентного тетраодонтимформа",
          "type": "main",
          "proteins": 44,
          "fat": 26,
          "carbohydrates": 85,
          "calories": 643,
          "price": 988,
          "image": "https://code.s3.yandex.net/react/code/meat-03.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-03-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733cc",
          "name": "Соус Spicy-X",
          "type": "sauce",
          "proteins": 30,
          "fat": 20,
          "carbohydrates": 40,
          "calories": 30,
          "price": 90,
          "image": "https://code.s3.yandex.net/react/code/sauce-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/sauce-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733cd",
          "name": "Соус фирменный Space Sauce",
          "type": "sauce",
          "proteins": 50,
          "fat": 22,
          "carbohydrates": 11,
          "calories": 14,
          "price": 80,
          "image": "https://code.s3.yandex.net/react/code/sauce-04.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/sauce-04-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/sauce-04-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733d0",
          "name": "Хрустящие минеральные кольца",
          "type": "main",
          "proteins": 808,
          "fat": 689,
          "carbohydrates": 609,
          "calories": 986,
          "price": 300,
          "image": "https://code.s3.yandex.net/react/code/mineral_rings.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/mineral_rings-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/mineral_rings-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733d0",
          "name": "Хрустящие минеральные кольца",
          "type": "main",
          "proteins": 808,
          "fat": 689,
          "carbohydrates": 609,
          "calories": 986,
          "price": 300,
          "image": "https://code.s3.yandex.net/react/code/mineral_rings.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/mineral_rings-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/mineral_rings-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c6",
          "name": "Краторная булка N-200i",
          "type": "bun",
          "proteins": 80,
          "fat": 24,
          "carbohydrates": 53,
          "calories": 420,
          "price": 1255,
          "image": "https://code.s3.yandex.net/react/code/bun-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
          "__v": 0
        }
      ],
      price: '666',
    },
    {
      id: '#222222',
      date: 'Сегодня, 16:20 i-GMT+3',
      name: 'Interstellar бургер',
      ingredients: [
        {
          "_id": "60d3b41abdacab0026a733c7",
          "name": "Флюоресцентная булка R2-D3",
          "type": "bun",
          "proteins": 44,
          "fat": 26,
          "carbohydrates": 85,
          "calories": 643,
          "price": 988,
          "image": "https://code.s3.yandex.net/react/code/bun-01.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/bun-01-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/bun-01-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c8",
          "name": "Филе Люминесцентного тетраодонтимформа",
          "type": "main",
          "proteins": 44,
          "fat": 26,
          "carbohydrates": 85,
          "calories": 643,
          "price": 988,
          "image": "https://code.s3.yandex.net/react/code/meat-03.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-03-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c7",
          "name": "Флюоресцентная булка R2-D3",
          "type": "bun",
          "proteins": 44,
          "fat": 26,
          "carbohydrates": 85,
          "calories": 643,
          "price": 988,
          "image": "https://code.s3.yandex.net/react/code/bun-01.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/bun-01-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/bun-01-large.png",
          "__v": 0
        }
      ],
      price: '1337',
    },
    {
      id: '#333333',
      date: 'Сегодня, 16:20 i-GMT+3',
      name: 'Black Hole Singularity острый бургер',
      ingredients: [
        {
          "_id": "60d3b41abdacab0026a733c6",
          "name": "Краторная булка N-200i",
          "type": "bun",
          "proteins": 80,
          "fat": 24,
          "carbohydrates": 53,
          "calories": 420,
          "price": 1255,
          "image": "https://code.s3.yandex.net/react/code/bun-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c6",
          "name": "Краторная булка N-200i",
          "type": "bun",
          "proteins": 80,
          "fat": 24,
          "carbohydrates": 53,
          "calories": 420,
          "price": 1255,
          "image": "https://code.s3.yandex.net/react/code/bun-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
          "__v": 0
        }
      ],
      price: '228',
    },
    {
      id: '#444444',
      date: 'Сегодня, 16:20 i-GMT+3',
      name: 'Supernova Infinity бургер',
      ingredients: [
        {
          "_id": "60d3b41abdacab0026a733c6",
          "name": "Краторная булка N-200i",
          "type": "bun",
          "proteins": 80,
          "fat": 24,
          "carbohydrates": 53,
          "calories": 420,
          "price": 1255,
          "image": "https://code.s3.yandex.net/react/code/bun-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c8",
          "name": "Филе Люминесцентного тетраодонтимформа",
          "type": "main",
          "proteins": 44,
          "fat": 26,
          "carbohydrates": 85,
          "calories": 643,
          "price": 988,
          "image": "https://code.s3.yandex.net/react/code/meat-03.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-03-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c6",
          "name": "Краторная булка N-200i",
          "type": "bun",
          "proteins": 80,
          "fat": 24,
          "carbohydrates": 53,
          "calories": 420,
          "price": 1255,
          "image": "https://code.s3.yandex.net/react/code/bun-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
          "__v": 0
        }
      ],
      price: '42',
    },
    {
      id: '#555555',
      date: 'Сегодня, 16:20 i-GMT+3',
      name: 'Death Start Starship Main бургер',
      ingredients: [
        {
          "_id": "60d3b41abdacab0026a733c6",
          "name": "Краторная булка N-200i",
          "type": "bun",
          "proteins": 80,
          "fat": 24,
          "carbohydrates": 53,
          "calories": 420,
          "price": 1255,
          "image": "https://code.s3.yandex.net/react/code/bun-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c8",
          "name": "Филе Люминесцентного тетраодонтимформа",
          "type": "main",
          "proteins": 44,
          "fat": 26,
          "carbohydrates": 85,
          "calories": 643,
          "price": 988,
          "image": "https://code.s3.yandex.net/react/code/meat-03.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-03-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c6",
          "name": "Краторная булка N-200i",
          "type": "bun",
          "proteins": 80,
          "fat": 24,
          "carbohydrates": 53,
          "calories": 420,
          "price": 1255,
          "image": "https://code.s3.yandex.net/react/code/bun-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
          "__v": 0
        }
      ],
      price: '13',
    },
    {
      id: '#666666',
      date: 'Сегодня, 16:20 i-GMT+3',
      name: 'Death Start Starship Main бургер',
      ingredients: [
        {
          "_id": "60d3b41abdacab0026a733c6",
          "name": "Краторная булка N-200i",
          "type": "bun",
          "proteins": 80,
          "fat": 24,
          "carbohydrates": 53,
          "calories": 420,
          "price": 1255,
          "image": "https://code.s3.yandex.net/react/code/bun-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c8",
          "name": "Филе Люминесцентного тетраодонтимформа",
          "type": "main",
          "proteins": 44,
          "fat": 26,
          "carbohydrates": 85,
          "calories": 643,
          "price": 988,
          "image": "https://code.s3.yandex.net/react/code/meat-03.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-03-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c6",
          "name": "Краторная булка N-200i",
          "type": "bun",
          "proteins": 80,
          "fat": 24,
          "carbohydrates": 53,
          "calories": 420,
          "price": 1255,
          "image": "https://code.s3.yandex.net/react/code/bun-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
          "__v": 0
        }
      ],
      price: '777',
    },
    {
      id: '#777777',
      date: 'Сегодня, 16:20 i-GMT+3',
      name: 'Death Start Starship Main бургер',
      ingredients: [
        {
          "_id": "60d3b41abdacab0026a733c6",
          "name": "Краторная булка N-200i",
          "type": "bun",
          "proteins": 80,
          "fat": 24,
          "carbohydrates": 53,
          "calories": 420,
          "price": 1255,
          "image": "https://code.s3.yandex.net/react/code/bun-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c8",
          "name": "Филе Люминесцентного тетраодонтимформа",
          "type": "main",
          "proteins": 44,
          "fat": 26,
          "carbohydrates": 85,
          "calories": 643,
          "price": 988,
          "image": "https://code.s3.yandex.net/react/code/meat-03.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-03-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c9",
          "name": "Мясо бессмертных моллюсков Protostomia",
          "type": "main",
          "proteins": 433,
          "fat": 244,
          "carbohydrates": 33,
          "calories": 420,
          "price": 1337,
          "image": "https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
          "__v": 0
        },
        {
          "_id": "60d3b41abdacab0026a733c6",
          "name": "Краторная булка N-200i",
          "type": "bun",
          "proteins": 80,
          "fat": 24,
          "carbohydrates": 53,
          "calories": 420,
          "price": 1255,
          "image": "https://code.s3.yandex.net/react/code/bun-02.png",
          "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
          "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
          "__v": 0
        }
      ],
      price: '666',
    }
]

export const dataOrdersNumbers = {
  ready: ['034533', '034532', '034530', '034527', '034525'],
  inWork: ['034533', '034532', '034530'],
  totalOrders: '28752',
  todayOrders: '138'
}
